### ISSUE TITLE
DEAFEN IN VOICE CHANNELS TO SAVE MEMORY

### ISSUE THREAD

**Issue by DrEngi** [DrEngi/lmao-bot#26]
# before
member.deaf
member.voice.voice_channel

# after
if member.voice: # can be None
    member.voice.deaf
    member.voice.channel

**Comment by DrEngi** [comment]
Solved by leaving after 15 minutes

**Comment by Firestar493** [comment]
Actually, I still want to check this out 🤔

**Comment by DrEngi** [comment]
I see how it is

**Comment by DrEngi** [comment]
Resolved with csharp launch
