### ISSUE TITLE
Loading server settings blocks the bot from sending keepalive messages to Discord

### ISSUE THREAD

**Issue by DrEngi** [DrEngi/lmao-bot#80]
Results in the bot often erroring out, disconnecting from discord, and reconnecting immediately, leading to poor startup times and sometimes poor performance

**Comment by Blizma** [comment]
This sounds like a job for Professor Firestar.

**Comment by DrEngi** [comment]
Unfortunately, Professor Firestar is _unavailable_. Nah, he's just busy with stuff, I'd love to help out with fixing these issues but my python expertise is rather poor and lmao's code has kinda spaghettied again.

I'd love it if we could convert to C# but somehow I think that'd cause issues

**Comment by DrEngi** [comment]
Update: Loading server settings took **5 minutes** on my machine, similar speeds to what is run on the server. I'm convinced there's a bunch of bullshit data that's in there which we no longer need.

**Comment by xMinota** [comment]
data-phobe

**Comment by DrEngi** [comment]
oh yeah it's because we have 5000+ lines of servers that no longer use lmao-bot still saved in the data directory, probably because we don't remove them when the bot leaves a server. To test it, I removed the excess servers on lmao-dev and loading times dropped from 5 minutes to about 20 seconds.

**Comment by DrEngi** [comment]
Likely issue is this here loop, which is blocking and runs for a while:
```python
        for guild in self.bot.guilds:
            # lbvars.update_settings(guild.id, lbvars.GuildSettings(guild.id))
            new_guild = lbvars.init_settings(guild.id)
            guild_count = lbvars.increment_guild_count()
            keyword = "OLD: "
            if new_guild:
                "NEW: "
            lbvars.LOGGER.info(str("#{}. {}{}.".format(guild_count, keyword, guild.name)))
```

**Comment by DrEngi** [comment]
Commenting out the above loop did indeed fix this issue, but the bot still takes a while to initially startup due to a significant amount of data in the JSON files. We'll probably need to figure out a way to automatically clean them up, but for now, this issue is resolved.
