### ISSUE TITLE
Data Storage Migration

### ISSUE THREAD

**Issue by DrEngi** [DrEngi/lmao-bot#99]
Probably gonna move to MySQL or Redis idk

**Comment by DrEngi** [comment]
Done, but we're migrating to MongoDB for data storage, because it's much more easily accessible and it completely fixes issues with loading times because we don't have to load every damn setting. Technically, it's good form to use a Web API to separate bot and database access, but I'm not doing this (even though we'll have a web API) because it makes development on a machine that isn't mine very difficult because it's just another thing people need to have running. And I'm also betting Mongo is more resilient than whatever web server I conjure up

**Comment by BradonZhang** [comment]
Cool. But would it really be better than SQL in this case if a lot of settings where the fields are the same? 🤔

Playlists are definitely something that would be best done with something like Mongo, though.

**Comment by DrEngi** [comment]
The difference is negligible tbh. Personally, I like Mongo better in this instance since it's based around JSON objects, which it makes conversion from our existing data a lot easier. It also converts to native objects is a much simpler fashion than SQL would. And, to be honest, if we're gonna use Mongo for one thing (playlists), might as well just use it for everything. 

The conversion is done, message me on discord and I can give you access to the database so you can see for yourself.

**Comment by DrEngi** [comment]
Resolved with rewrite launch
